function varargout = vlc_wrapper(task, varargin)

    tasks = {'init'   , ...
             'release', ...
             'open'   , ...
             'close'  , ...
             'frame'  , ...
             'play'   , ...
             'pause'  , ...
             'info'   , ...
             'cleanup'};
    
    [varargout{1:nargout}] = vlc(find(strcmpi(task, tasks))-1, varargin{:});

end
